[package]
name         = "dmac-plugin"
version.workspace      = true
edition.workspace      = true
rust-version.workspace = true
license.workspace      = true
repository.workspace   = true
authors.workspace      = true
description  = "WASM and Lua plugin host."

[lints]
workspace = true

[dependencies]
