[package]
name         = "dmac-config"
version.workspace      = true
edition.workspace      = true
rust-version.workspace = true
license.workspace      = true
repository.workspace   = true
authors.workspace      = true
description  = "Configuration, keymaps and themes for DMACommander."

[lints]
workspace = true

[dependencies]
